# Generated by Django 5.2.4 on 2025-08-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_instructoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
