# Generated by Django 5.2.4 on 2025-08-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='review',
        ),
    ]
